// 100 Coding Challenges — 25 Easy, 25 Medium, 25 Hard, 25 Extreme
// Each challenge: { id, title, difficulty, category, description, hint, starterCode, tests }

function ch(id, title, difficulty, category, description, hint, jsStarter, pyStarter, expectedOutput, solution) {
    return {
        id, title, difficulty, category, description, hint,
        starterCode: {
            javascript: jsStarter,
            python: pyStarter
        },
        tests: [{ input: '', expectedOutput }],
        solution: solution || ''
    };
}

// ===================== EASY (25) =====================
const EASY = [
    ch('e1', 'Hello World', 'easy', 'basics', 'Print "Hello, World!" to the console.', 'Use console.log() or print().',
        '// Print "Hello, World!"\n', '# Print "Hello, World!"\n', 'Hello, World!'),
    ch('e2', 'Sum Two Numbers', 'easy', 'basics', 'Print the sum of 3 and 5.', 'Just add them and print.',
        '// Print 3 + 5\n', '# Print 3 + 5\n', '8'),
    ch('e3', 'Even or Odd', 'easy', 'basics', 'Print "Even" if 4 is even, "Odd" if 7 is odd. Print both results.', 'Use modulo operator %.',
        '// Check 4 and 7\n', '# Check 4 and 7\n', 'Even\nOdd'),
    ch('e4', 'Max of Two', 'easy', 'basics', 'Print the maximum of 10 and 25.', 'Compare with > or use Math.max/max.',
        '// Print max of 10 and 25\n', '# Print max of 10 and 25\n', '25'),
    ch('e5', 'String Length', 'easy', 'strings', 'Print the length of "CodeForge".', 'Use .length or len().',
        '// Print length of "CodeForge"\n', '# Print length of "CodeForge"\n', '9'),
    ch('e6', 'Reverse String', 'easy', 'strings', 'Print "hello" reversed.', 'Convert to array, reverse, join back.',
        '// Print "hello" reversed\n', '# Print "hello" reversed\n', 'olleh'),
    ch('e7', 'Count Vowels', 'easy', 'strings', 'Print the number of vowels in "programming".', 'Check each char against aeiou.',
        '// Count vowels in "programming"\n', '# Count vowels in "programming"\n', '3'),
    ch('e8', 'Absolute Value', 'easy', 'math', 'Print the absolute value of -42.', 'Use Math.abs() or abs().',
        '// Print absolute of -42\n', '# Print absolute of -42\n', '42'),
    ch('e9', 'Celsius to Fahrenheit', 'easy', 'math', 'Convert 100°C to Fahrenheit (F = C×9/5+32). Print the result.', 'Multiply by 9/5 and add 32.',
        '// Convert 100C to F\n', '# Convert 100C to F\n', '212'),
    ch('e10', 'Swap Variables', 'easy', 'basics', 'Given a=5, b=10, swap them and print "a=10 b=5".', 'Use a temp variable or destructuring.',
        '// Swap a=5 and b=10, print "a=10 b=5"\n', '# Swap a=5 and b=10, print "a=10 b=5"\n', 'a=10 b=5'),
    ch('e11', 'Multiplication Table', 'easy', 'loops', 'Print the multiplication table of 5 from 5x1 to 5x5 (format: "5 x 1 = 5").', 'Use a loop from 1 to 5.',
        '// Print 5x table\n', '# Print 5x table\n', '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25'),
    ch('e12', 'Sum 1 to 10', 'easy', 'loops', 'Print the sum of numbers from 1 to 10.', 'Use a loop or formula n*(n+1)/2.',
        '// Sum 1 to 10\n', '# Sum 1 to 10\n', '55'),
    ch('e13', 'Array Sum', 'easy', 'arrays', 'Print the sum of [1,2,3,4,5].', 'Loop through and accumulate.',
        '// Sum of [1,2,3,4,5]\n', '# Sum of [1,2,3,4,5]\n', '15'),
    ch('e14', 'Find Minimum', 'easy', 'arrays', 'Print the minimum value in [8,3,7,1,5].', 'Track the smallest while looping.',
        '// Min of [8,3,7,1,5]\n', '# Min of [8,3,7,1,5]\n', '1'),
    ch('e15', 'Count Down', 'easy', 'loops', 'Print numbers from 5 down to 1, each on a new line.', 'Use a loop counting backwards.',
        '// Count from 5 to 1\n', '# Count from 5 to 1\n', '5\n4\n3\n2\n1'),
    ch('e16', 'Square Number', 'easy', 'math', 'Print the square of 7.', 'Multiply it by itself.',
        '// Print 7 squared\n', '# Print 7 squared\n', '49'),
    ch('e17', 'Is Positive', 'easy', 'basics', 'Print "positive" for 10, "negative" for -3, "zero" for 0.', 'Use if/else if/else.',
        '// Check 10, -3, 0\n', '# Check 10, -3, 0\n', 'positive\nnegative\nzero'),
    ch('e18', 'First and Last', 'easy', 'strings', 'Print the first and last character of "JavaScript" separated by space.', 'Access index 0 and last index.',
        '// First and last of "JavaScript"\n', '# First and last of "JavaScript"\n', 'J t'),
    ch('e19', 'Repeat String', 'easy', 'strings', 'Print "ha" repeated 3 times as "hahaha".', 'Use .repeat() or * operator.',
        '// Repeat "ha" 3 times\n', '# Repeat "ha" 3 times\n', 'hahaha'),
    ch('e20', 'Check Leap Year', 'easy', 'math', 'Print "true" if 2024 is a leap year, "false" if not.', 'Divisible by 4, not 100, or by 400.',
        '// Is 2024 a leap year?\n', '# Is 2024 a leap year?\n', 'true'),
    ch('e21', 'String Uppercase', 'easy', 'strings', 'Print "hello world" in uppercase.', 'Use .toUpperCase() or .upper().',
        '// Uppercase "hello world"\n', '# Uppercase "hello world"\n', 'HELLO WORLD'),
    ch('e22', 'Array Contains', 'easy', 'arrays', 'Print "found" if 3 is in [1,2,3,4,5], else "not found".', 'Use includes() or in operator.',
        '// Check if 3 in [1,2,3,4,5]\n', '# Check if 3 in [1,2,3,4,5]\n', 'found'),
    ch('e23', 'Factorial', 'easy', 'math', 'Print the factorial of 5 (5! = 120).', 'Multiply 1*2*3*4*5.',
        '// Print 5!\n', '# Print 5!\n', '120'),
    ch('e24', 'Join Words', 'easy', 'arrays', 'Join ["Code","Forge","Editor"] with "-" and print.', 'Use .join("-") or "-".join().',
        '// Join with dash\n', '# Join with dash\n', 'Code-Forge-Editor'),
    ch('e25', 'Power of Two', 'easy', 'math', 'Print "true" if 16 is a power of 2, "false" for 12.', 'Keep dividing by 2, check if you reach 1.',
        '// Check 16 and 12\n', '# Check 16 and 12\n', 'true\nfalse'),
];

// ===================== MEDIUM (25) =====================
const MEDIUM = [
    ch('m1', 'Fibonacci Sequence', 'medium', 'algorithms', 'Print the first 10 Fibonacci numbers each on a new line.', 'Each number is sum of two preceding ones.',
        '// First 10 Fibonacci\n', '# First 10 Fibonacci\n', '0\n1\n1\n2\n3\n5\n8\n13\n21\n34'),
    ch('m2', 'Palindrome Check', 'medium', 'strings', 'Print "true" for "racecar", "false" for "hello".', 'Compare string with its reverse.',
        '// Palindrome check\n', '# Palindrome check\n', 'true\nfalse'),
    ch('m3', 'FizzBuzz', 'medium', 'classics', 'Print 1-20: "Fizz" for ×3, "Buzz" for ×5, "FizzBuzz" for both.', 'Check 15 first, then 3, then 5.',
        '// FizzBuzz 1-20\n', '# FizzBuzz 1-20\n', '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz'),
    ch('m4', 'Remove Duplicates', 'medium', 'arrays', 'Remove duplicates from [1,2,2,3,4,4,5] and print as "1,2,3,4,5".', 'Use a Set or filter.',
        '// Remove duplicates\n', '# Remove duplicates\n', '1,2,3,4,5'),
    ch('m5', 'Count Words', 'medium', 'strings', 'Print the number of words in "The quick brown fox jumps".', 'Split by space and count.',
        '// Count words\n', '# Count words\n', '5'),
    ch('m6', 'Sort Array', 'medium', 'arrays', 'Sort [5,2,8,1,9,3] ascending and print as "1,2,3,5,8,9".', 'Implement bubble sort or use built-in sort.',
        '// Sort ascending\n', '# Sort ascending\n', '1,2,3,5,8,9'),
    ch('m7', 'Title Case', 'medium', 'strings', 'Convert "hello world foo" to "Hello World Foo".', 'Capitalize first letter of each word.',
        '// Title case\n', '# Title case\n', 'Hello World Foo'),
    ch('m8', 'Sum of Digits', 'medium', 'math', 'Print the sum of digits of 12345.', 'Extract each digit with % 10.',
        '// Sum digits of 12345\n', '# Sum digits of 12345\n', '15'),
    ch('m9', 'Prime Check', 'medium', 'algorithms', 'Print "true" if 17 is prime, "false" for 15.', 'Check divisibility up to sqrt(n).',
        '// Prime check 17 and 15\n', '# Prime check 17 and 15\n', 'true\nfalse'),
    ch('m10', 'Matrix Diagonal', 'medium', 'arrays', 'Print the diagonal sum of [[1,2,3],[4,5,6],[7,8,9]].', 'Sum elements where row index = col index.',
        '// Diagonal sum\n', '# Diagonal sum\n', '15'),
    ch('m11', 'Anagram Check', 'medium', 'strings', 'Print "true" if "listen" and "silent" are anagrams, "false" for "hello" and "world".', 'Sort both strings and compare.',
        '// Anagram check\n', '# Anagram check\n', 'true\nfalse'),
    ch('m12', 'Second Largest', 'medium', 'arrays', 'Print the second largest number in [3,1,4,1,5,9,2].', 'Sort or track two max values.',
        '// Second largest\n', '# Second largest\n', '5'),
    ch('m13', 'String Compression', 'medium', 'strings', 'Compress "aaabbbccdd" to "a3b3c2d2". Print result.', 'Count consecutive chars.',
        '// Compress string\n', '# Compress string\n', 'a3b3c2d2'),
    ch('m14', 'Common Elements', 'medium', 'arrays', 'Print common elements of [1,2,3,4] and [3,4,5,6] as "3,4".', 'Check if each element exists in both.',
        '// Common elements\n', '# Common elements\n', '3,4'),
    ch('m15', 'Reverse Words', 'medium', 'strings', 'Reverse word order in "Hello World Foo" to "Foo World Hello".', 'Split, reverse, join.',
        '// Reverse words\n', '# Reverse words\n', 'Foo World Hello'),
    ch('m16', 'GCD', 'medium', 'math', 'Print the GCD of 48 and 18.', 'Use Euclidean algorithm.',
        '// GCD of 48 and 18\n', '# GCD of 48 and 18\n', '6'),
    ch('m17', 'Flatten Array', 'medium', 'arrays', 'Flatten [1,[2,[3,4]],5] and print as "1,2,3,4,5".', 'Use recursion or flat().',
        '// Flatten nested array\n', '# Flatten nested list\n', '1,2,3,4,5'),
    ch('m18', 'Caesar Cipher', 'medium', 'strings', 'Shift "abc" by 3 to get "def". Print result.', 'Add offset to char code, wrap at z.',
        '// Caesar cipher shift 3\n', '# Caesar cipher shift 3\n', 'def'),
    ch('m19', 'Array Rotation', 'medium', 'arrays', 'Rotate [1,2,3,4,5] left by 2 positions. Print "3,4,5,1,2".', 'Slice and concatenate.',
        '// Rotate left by 2\n', '# Rotate left by 2\n', '3,4,5,1,2'),
    ch('m20', 'Number to Roman', 'medium', 'math', 'Convert 42 to Roman numerals. Print "XLII".', 'Subtract largest Roman values greedily.',
        '// 42 to Roman\n', '# 42 to Roman\n', 'XLII'),
    ch('m21', 'Balanced Parens', 'medium', 'strings', 'Print "true" if "(())()" is balanced, "false" for "(()" .', 'Use a counter or stack.',
        '// Check balanced\n', '# Check balanced\n', 'true\nfalse'),
    ch('m22', 'Pascal Triangle Row', 'medium', 'math', 'Print row 5 of Pascals triangle as "1,5,10,10,5,1".', 'Each element = C(n,k).',
        '// Pascal row 5\n', '# Pascal row 5\n', '1,5,10,10,5,1'),
    ch('m23', 'Unique Characters', 'medium', 'strings', 'Print "true" if "abcdef" has all unique chars, "false" for "aabcde".', 'Use a Set to track seen chars.',
        '// Unique char check\n', '# Unique char check\n', 'true\nfalse'),
    ch('m24', 'Array Chunk', 'medium', 'arrays', 'Split [1,2,3,4,5,6,7] into chunks of 3. Print "1,2,3|4,5,6|7".', 'Loop with step of chunk size.',
        '// Chunk by 3\n', '# Chunk by 3\n', '1,2,3|4,5,6|7'),
    ch('m25', 'Binary Convert', 'medium', 'math', 'Convert 42 to binary string. Print "101010".', 'Divide by 2 repeatedly, collect remainders.',
        '// 42 to binary\n', '# 42 to binary\n', '101010'),
];

// ===================== HARD (25) =====================
const HARD = [
    ch('h1', 'Binary Search', 'hard', 'algorithms', 'Find index of 7 in [1,3,5,7,9,11,13]. Print the index.', 'Compare mid, search correct half.',
        '// Binary search for 7\n', '# Binary search for 7\n', '3'),
    ch('h2', 'Merge Sort', 'hard', 'algorithms', 'Sort [38,27,43,3,9,82,10] using merge sort. Print "3,9,10,27,38,43,82".', 'Divide in half, sort each, merge.',
        '// Merge sort\n', '# Merge sort\n', '3,9,10,27,38,43,82'),
    ch('h3', 'Longest Substring', 'hard', 'strings', 'Find length of longest substring without repeating chars in "abcabcbb". Print 3.', 'Sliding window with a set.',
        '// Longest unique substring\n', '# Longest unique substring\n', '3'),
    ch('h4', 'Valid Sudoku Row', 'hard', 'algorithms', 'Check if [5,3,4,6,7,2,1,9,8] is a valid sudoku row (1-9 each once). Print "true".', 'Check all digits 1-9 appear exactly once.',
        '// Valid sudoku row\n', '# Valid sudoku row\n', 'true'),
    ch('h5', 'Spiral Matrix', 'hard', 'arrays', 'Print a 3x3 matrix [[1,2,3],[4,5,6],[7,8,9]] in spiral order as "1,2,3,6,9,8,7,4,5".', 'Track boundaries, shrink inward.',
        '// Spiral order\n', '# Spiral order\n', '1,2,3,6,9,8,7,4,5'),
    ch('h6', 'Two Sum', 'hard', 'algorithms', 'Find indices of two numbers in [2,7,11,15] that sum to 9. Print "0,1".', 'Use a hash map for O(n) lookup.',
        '// Two sum target=9\n', '# Two sum target=9\n', '0,1'),
    ch('h7', 'LRU Cache', 'hard', 'data structures', 'Implement an LRU cache(2): put(1,1), put(2,2), get(1)→print 1, put(3,3), get(2)→print -1.', 'Use Map for order tracking.',
        '// LRU Cache\n', '# LRU Cache\n', '1\n-1'),
    ch('h8', 'Valid Parentheses', 'hard', 'strings', 'Check "({[]})" → "true", "({[})" → "false". Print both.', 'Use stack, match closing with opening.',
        '// Valid parens check\n', '# Valid parens check\n', 'true\nfalse'),
    ch('h9', 'Primes to 50', 'hard', 'algorithms', 'Print all primes from 2 to 50 each on a new line.', 'Sieve of Eratosthenes.',
        '// Primes 2-50\n', '# Primes 2-50\n', '2\n3\n5\n7\n11\n13\n17\n19\n23\n29\n31\n37\n41\n43\n47'),
    ch('h10', 'Max Subarray', 'hard', 'algorithms', 'Find max contiguous subarray sum of [-2,1,-3,4,-1,2,1,-5,4]. Print 6.', 'Kadanes algorithm.',
        '// Max subarray sum\n', '# Max subarray sum\n', '6'),
    ch('h11', 'Linked List Cycle', 'hard', 'data structures', 'Simulate: print "has cycle" if a list has a cycle, else "no cycle". Test with [1,2,3,2].', 'Floyd tortoise and hare.',
        '// Detect cycle in [1,2,3] with 3->2\nconsole.log("has cycle");\n', '# Detect cycle in [1,2,3] with 3->2\nprint("has cycle")\n', 'has cycle'),
    ch('h12', 'Matrix Rotate', 'hard', 'arrays', 'Rotate [[1,2,3],[4,5,6],[7,8,9]] 90° clockwise. Print rows: "7,4,1|8,5,2|9,6,3".', 'Transpose then reverse each row.',
        '// Rotate matrix 90\n', '# Rotate matrix 90\n', '7,4,1|8,5,2|9,6,3'),
    ch('h13', 'Group Anagrams', 'hard', 'strings', 'Group ["eat","tea","tan","ate","nat","bat"]. Print group count: 3.', 'Sort each word as key in a map.',
        '// Group anagrams count\n', '# Group anagrams count\n', '3'),
    ch('h14', 'Power Set', 'hard', 'algorithms', 'Print the count of subsets of [1,2,3]. Should be 8.', 'Each element is either in or out: 2^n.',
        '// Power set count\n', '# Power set count\n', '8'),
    ch('h15', 'Longest Palindrome', 'hard', 'strings', 'Find the longest palindromic substring in "babad". Print "bab".', 'Expand around center for each position.',
        '// Longest palindrome\n', '# Longest palindrome\n', 'bab'),
    ch('h16', 'Merge Intervals', 'hard', 'arrays', 'Merge [[1,3],[2,6],[8,10],[15,18]]. Print "1,6|8,10|15,18".', 'Sort by start, merge overlapping.',
        '// Merge intervals\n', '# Merge intervals\n', '1,6|8,10|15,18'),
    ch('h17', 'BFS Shortest Path', 'hard', 'algorithms', 'In a 3x3 grid, find shortest path from (0,0) to (2,2). Print distance: 4.', 'Use BFS with queue.',
        '// BFS shortest path\n', '# BFS shortest path\n', '4'),
    ch('h18', 'Stack with Min', 'hard', 'data structures', 'Push 5,3,7,2. Print min after each push: "5,3,3,2".', 'Maintain a parallel min stack.',
        '// Min stack\n', '# Min stack\n', '5,3,3,2'),
    ch('h19', 'Longest Common Prefix', 'hard', 'strings', 'Find LCP of ["flower","flow","flight"]. Print "fl".', 'Compare char by char across all strings.',
        '// Longest common prefix\n', '# Longest common prefix\n', 'fl'),
    ch('h20', 'Top K Frequent', 'hard', 'arrays', 'Find top 2 frequent in [1,1,1,2,2,3]. Print "1,2".', 'Use frequency map, sort by count.',
        '// Top 2 frequent\n', '# Top 2 frequent\n', '1,2'),
    ch('h21', 'Quick Select', 'hard', 'algorithms', 'Find 3rd smallest in [7,10,4,3,20,15]. Print 7.', 'Partition like quicksort.',
        '// 3rd smallest\n', '# 3rd smallest\n', '7'),
    ch('h22', 'Decode String', 'hard', 'strings', 'Decode "3[a2[c]]" to "accaccacc". Print result.', 'Use stack for nested patterns.',
        '// Decode string\n', '# Decode string\n', 'accaccacc'),
    ch('h23', 'Product Except Self', 'hard', 'arrays', 'For [1,2,3,4] print product of all except self: "24,12,8,6".', 'Left pass then right pass.',
        '// Product except self\n', '# Product except self\n', '24,12,8,6'),
    ch('h24', 'Trie Insert Search', 'hard', 'data structures', 'Insert "apple","app" into trie. search("apple")→true, search("app")→false, startsWith("app")→true.', 'Trie node with children map and endOfWord flag.',
        '// Trie operations\n', '# Trie operations\n', 'true\nfalse\ntrue'),
    ch('h25', 'Coin Change', 'hard', 'algorithms', 'Find min coins for amount 11 from [1,5,6]. Print 2.', 'Dynamic programming bottom-up.',
        '// Min coins for 11\n', '# Min coins for 11\n', '2'),
];

// ===================== EXTREME (25) =====================
const EXTREME = [
    ch('x1', 'N-Queens Count', 'extreme', 'algorithms', 'Count solutions for 4-Queens problem. Print 2.', 'Backtracking with column/diagonal tracking.',
        '// 4-Queens solutions\n', '# 4-Queens solutions\n', '2'),
    ch('x2', 'LIS Length', 'extreme', 'algorithms', 'Find length of Longest Increasing Subsequence of [10,9,2,5,3,7,101,18]. Print 4.', 'DP or binary search approach.',
        '// LIS length\n', '# LIS length\n', '4'),
    ch('x3', 'Edit Distance', 'extreme', 'strings', 'Find min edits to convert "horse" to "ros". Print 3.', 'DP matrix comparing chars.',
        '// Edit distance\n', '# Edit distance\n', '3'),
    ch('x4', 'Knapsack 0/1', 'extreme', 'algorithms', 'Weights [1,3,4,5], values [1,4,5,7], capacity 7. Print max value: 9.', 'DP table over items and capacity.',
        '// 0/1 Knapsack\n', '# 0/1 Knapsack\n', '9'),
    ch('x5', 'Median Two Arrays', 'extreme', 'algorithms', 'Find median of [1,3] and [2]. Print 2.', 'Binary search on shorter array.',
        '// Median of two arrays\n', '# Median of two arrays\n', '2'),
    ch('x6', 'Serialize Tree', 'extreme', 'data structures', 'Serialize tree [1,2,3,null,null,4,5] to string then deserialize. Print root value: 1.', 'Use preorder with null markers.',
        '// Serialize/deserialize tree\n', '# Serialize/deserialize tree\n', '1'),
    ch('x7', 'Word Break', 'extreme', 'algorithms', 'Can "leetcode" be segmented into ["leet","code"]? Print "true".', 'DP checking all prefixes.',
        '// Word break\n', '# Word break\n', 'true'),
    ch('x8', 'Max Profit Trades', 'extreme', 'algorithms', 'Max profit from [3,3,5,0,0,3,1,4] with at most 2 transactions. Print 6.', 'State machine DP.',
        '// Max profit 2 trades\n', '# Max profit 2 trades\n', '6'),
    ch('x9', 'Longest Valid Parens', 'extreme', 'strings', 'Find length of longest valid parentheses in "(()(). Print 4.', 'Stack-based approach tracking indices.',
        '// Longest valid parens\n', '# Longest valid parens\n', '4'),
    ch('x10', 'Sudoku Solver', 'extreme', 'algorithms', 'Solve a sudoku: for a partially filled 4x4 grid, print "solved".', 'Backtracking with constraint checking.',
        '// Sudoku solver\nconsole.log("solved");\n', '# Sudoku solver\nprint("solved")\n', 'solved'),
    ch('x11', 'Regex Matching', 'extreme', 'strings', 'Match "aab" against "c*a*b": print "true". Match "ab" against ".*": print "true".', 'DP comparing pattern and string.',
        '// Regex matching\n', '# Regex matching\n', 'true\ntrue'),
    ch('x12', 'Trapping Rain Water', 'extreme', 'arrays', 'Calculate trapped water for [0,1,0,2,1,0,1,3,2,1,2,1]. Print 6.', 'Two pointer or prefix max arrays.',
        '// Trapping rain water\n', '# Trapping rain water\n', '6'),
    ch('x13', 'Word Ladder Length', 'extreme', 'algorithms', 'Transform "hit" to "cog" via ["hot","dot","dog","lot","log","cog"]. Print 5.', 'BFS with word graph.',
        '// Word ladder\n', '# Word ladder\n', '5'),
    ch('x14', 'Skyline Problem', 'extreme', 'algorithms', 'Buildings [[2,9,10],[3,7,15],[5,12,12]]. Print key points count: 5.', 'Sweep line with max-heap.',
        '// Skyline key points\n', '# Skyline key points\n', '5'),
    ch('x15', 'Minimum Window Sub', 'extreme', 'strings', 'Min window in "ADOBECODEBANC" containing "ABC". Print "BANC".', 'Sliding window with char frequency.',
        '// Min window substring\n', '# Min window substring\n', 'BANC'),
    ch('x16', 'Count Inversions', 'extreme', 'algorithms', 'Count inversions in [2,4,1,3,5]. Print 3.', 'Modified merge sort.',
        '// Count inversions\n', '# Count inversions\n', '3'),
    ch('x17', 'Largest Rectangle', 'extreme', 'arrays', 'Largest rectangle in histogram [2,1,5,6,2,3]. Print 10.', 'Stack-based O(n) solution.',
        '// Largest rectangle\n', '# Largest rectangle\n', '10'),
    ch('x18', 'Dijkstra Shortest', 'extreme', 'algorithms', 'Shortest path in weighted graph from 0 to 4 with 5 nodes. Print distance: 7.', 'Priority queue with relaxation.',
        '// Dijkstra\nconst graph = {0:{1:2,2:4}, 1:{2:1,3:7}, 2:{4:3}, 3:{4:1}, 4:{}};\n// Find shortest 0->4\n',
        '# Dijkstra\ngraph = {0:{1:2,2:4}, 1:{2:1,3:7}, 2:{4:3}, 3:{4:1}, 4:{}}\n# Find shortest 0->4\n', '7'),
    ch('x19', 'Topological Sort', 'extreme', 'algorithms', 'Topological sort of DAG with 4 nodes. Print one valid ordering.', 'DFS with finish-time stack, or Kahns algorithm.',
        '// Topological sort\n// Edges: 0->1, 0->2, 1->3, 2->3\nconsole.log("0,1,2,3");\n',
        '# Topological sort\n# Edges: 0->1, 0->2, 1->3, 2->3\nprint("0,1,2,3")\n', '0,1,2,3'),
    ch('x20', 'String Interleave', 'extreme', 'strings', 'Check if "aadbbcbcac" is interleaving of "aabcc" and "dbbca". Print "true".', '2D DP table.',
        '// String interleave check\n', '# String interleave check\n', 'true'),
    ch('x21', 'Max Flow', 'extreme', 'algorithms', 'Find max flow from source(0) to sink(3) in network. Print 5.', 'Ford-Fulkerson / BFS augmenting paths.',
        '// Max flow 0->3\nconsole.log(5);\n', '# Max flow 0->3\nprint(5)\n', '5'),
    ch('x22', 'KMP Pattern Match', 'extreme', 'strings', 'Find all occurrences of "ABAB" in "ABABDABACDABABCABAB". Print indices "0,10,14".', 'Build failure function, slide pattern.',
        '// KMP matching\n', '# KMP matching\n', '0,10,14'),
    ch('x23', 'Segment Tree Query', 'extreme', 'data structures', 'Build segment tree for [1,3,5,7,9,11]. Range sum query (1,3). Print 15.', 'Build tree, query range.',
        '// Segment tree range sum\n', '# Segment tree range sum\n', '15'),
    ch('x24', 'Convex Hull Points', 'extreme', 'algorithms', 'Find convex hull size of [(0,0),(1,1),(2,2),(0,2),(2,0),(1,0)]. Print 4.', 'Graham scan or Andrew monotone chain.',
        '// Convex hull\n', '# Convex hull\n', '4'),
    ch('x25', 'Suffix Array', 'extreme', 'strings', 'Build suffix array for "banana". Print first 3 sorted suffix indices: "5,3,1".', 'Sort all suffixes, return indices.',
        '// Suffix array\n', '# Suffix array\n', '5,3,1'),
];

export const ALL_CHALLENGES = [...EASY, ...MEDIUM, ...HARD, ...EXTREME];

// ===================== SOLUTIONS =====================
const SOLUTIONS = {
    // EASY
    e1: `console.log("Hello, World!");`,
    e2: `console.log(3 + 5);`,
    e3: `console.log(4 % 2 === 0 ? "Even" : "Odd");\nconsole.log(7 % 2 === 0 ? "Even" : "Odd");`,
    e4: `console.log(Math.max(10, 25));`,
    e5: `console.log("CodeForge".length);`,
    e6: `console.log("hello".split("").reverse().join(""));`,
    e7: `console.log("programming".split("").filter(c => "aeiou".includes(c)).length);`,
    e8: `console.log(Math.abs(-42));`,
    e9: `console.log(100 * 9 / 5 + 32);`,
    e10: `let a = 5, b = 10; [a, b] = [b, a]; console.log("a=" + a + " b=" + b);`,
    e11: `for (let i = 1; i <= 5; i++) console.log("5 x " + i + " = " + (5 * i));`,
    e12: `let s = 0; for (let i = 1; i <= 10; i++) s += i; console.log(s);`,
    e13: `console.log([1,2,3,4,5].reduce((a, b) => a + b, 0));`,
    e14: `console.log(Math.min(...[8,3,7,1,5]));`,
    e15: `for (let i = 5; i >= 1; i--) console.log(i);`,
    e16: `console.log(7 * 7);`,
    e17: `[10, -3, 0].forEach(n => console.log(n > 0 ? "positive" : n < 0 ? "negative" : "zero"));`,
    e18: `const s = "JavaScript"; console.log(s[0] + " " + s[s.length - 1]);`,
    e19: `console.log("ha".repeat(3));`,
    e20: `const y = 2024; console.log((y % 4 === 0 && y % 100 !== 0) || y % 400 === 0);`,
    e21: `console.log("hello world".toUpperCase());`,
    e22: `console.log([1,2,3,4,5].includes(3) ? "found" : "not found");`,
    e23: `let f = 1; for (let i = 2; i <= 5; i++) f *= i; console.log(f);`,
    e24: `console.log(["Code","Forge","Editor"].join("-"));`,
    e25: `function isPow2(n) { while (n > 1) { if (n % 2 !== 0) return false; n /= 2; } return n === 1; }\nconsole.log(isPow2(16));\nconsole.log(isPow2(12));`,
    // MEDIUM
    m1: `let a = 0, b = 1; for (let i = 0; i < 10; i++) { console.log(a); [a, b] = [b, a + b]; }`,
    m2: `function isPal(s) { return s === s.split("").reverse().join(""); }\nconsole.log(isPal("racecar"));\nconsole.log(isPal("hello"));`,
    m3: `for (let i = 1; i <= 20; i++) console.log(i % 15 === 0 ? "FizzBuzz" : i % 3 === 0 ? "Fizz" : i % 5 === 0 ? "Buzz" : i);`,
    m4: `console.log([...new Set([1,2,2,3,4,4,5])].join(","));`,
    m5: `console.log("The quick brown fox jumps".split(" ").length);`,
    m6: `console.log([5,2,8,1,9,3].sort((a,b) => a - b).join(","));`,
    m7: `console.log("hello world foo".split(" ").map(w => w[0].toUpperCase() + w.slice(1)).join(" "));`,
    m8: `let n = 12345, s = 0; while (n > 0) { s += n % 10; n = Math.floor(n / 10); } console.log(s);`,
    m9: `function isPrime(n) { if (n < 2) return false; for (let i = 2; i <= Math.sqrt(n); i++) if (n % i === 0) return false; return true; }\nconsole.log(isPrime(17));\nconsole.log(isPrime(15));`,
    m10: `const m = [[1,2,3],[4,5,6],[7,8,9]]; let s = 0; for (let i = 0; i < 3; i++) s += m[i][i]; console.log(s);`,
    m11: `function isAnagram(a, b) { return a.split("").sort().join("") === b.split("").sort().join(""); }\nconsole.log(isAnagram("listen", "silent"));\nconsole.log(isAnagram("hello", "world"));`,
    m12: `const arr = [3,1,4,1,5,9,2]; const sorted = [...new Set(arr)].sort((a,b) => b - a); console.log(sorted[1]);`,
    m13: `let r = "", c = 1; for (let i = 1; i < "aaabbbccdd".length; i++) { if ("aaabbbccdd"[i] === "aaabbbccdd"[i-1]) c++; else { r += "aaabbbccdd"[i-1] + c; c = 1; } } r += "aaabbbccdd".slice(-1) + c; console.log(r);`,
    m14: `console.log([1,2,3,4].filter(x => [3,4,5,6].includes(x)).join(","));`,
    m15: `console.log("Hello World Foo".split(" ").reverse().join(" "));`,
    m16: `function gcd(a, b) { while (b) { [a, b] = [b, a % b]; } return a; } console.log(gcd(48, 18));`,
    m17: `function flat(a) { return a.reduce((r, v) => r.concat(Array.isArray(v) ? flat(v) : v), []); } console.log(flat([1,[2,[3,4]],5]).join(","));`,
    m18: `console.log("abc".split("").map(c => String.fromCharCode(c.charCodeAt(0) + 3)).join(""));`,
    m19: `const a = [1,2,3,4,5]; console.log([...a.slice(2), ...a.slice(0, 2)].join(","));`,
    m20: `function toRoman(n) { const v = [[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]]; let r = ""; for (const [val, sym] of v) { while (n >= val) { r += sym; n -= val; } } return r; } console.log(toRoman(42));`,
    m21: `function bal(s) { let c = 0; for (const ch of s) { if (ch === "(") c++; else c--; if (c < 0) return false; } return c === 0; }\nconsole.log(bal("(())()"));\nconsole.log(bal("(()"));`,
    m22: `function pascal(n) { let r = [1]; for (let i = 1; i <= n; i++) r.push(r[i-1] * (n - i + 1) / i); return r; } console.log(pascal(5).join(","));`,
    m23: `console.log(new Set("abcdef").size === "abcdef".length);\nconsole.log(new Set("aabcde").size === "aabcde".length);`,
    m24: `const a = [1,2,3,4,5,6,7]; const r = []; for (let i = 0; i < a.length; i += 3) r.push(a.slice(i, i+3).join(",")); console.log(r.join("|"));`,
    m25: `console.log((42).toString(2));`,
    // HARD
    h1: `function bs(arr, t) { let l = 0, r = arr.length - 1; while (l <= r) { const m = Math.floor((l+r)/2); if (arr[m] === t) return m; arr[m] < t ? l = m+1 : r = m-1; } return -1; } console.log(bs([1,3,5,7,9,11,13], 7));`,
    h2: `function ms(a) { if (a.length <= 1) return a; const m = Math.floor(a.length/2); const l = ms(a.slice(0,m)), r = ms(a.slice(m)); const res = []; let i=0,j=0; while (i<l.length&&j<r.length) res.push(l[i]<r[j]?l[i++]:r[j++]); return res.concat(l.slice(i),r.slice(j)); } console.log(ms([38,27,43,3,9,82,10]).join(","));`,
    h3: `let max = 0, start = 0; const set = new Set(); for (let end = 0; end < "abcabcbb".length; end++) { while (set.has("abcabcbb"[end])) set.delete("abcabcbb"[start++]); set.add("abcabcbb"[end]); max = Math.max(max, end - start + 1); } console.log(max);`,
    h4: `console.log(new Set([5,3,4,6,7,2,1,9,8]).size === 9);`,
    h5: `const m = [[1,2,3],[4,5,6],[7,8,9]]; const r = []; let t=0,b=2,l=0,ri=2; while(t<=b&&l<=ri){for(let i=l;i<=ri;i++)r.push(m[t][i]);t++;for(let i=t;i<=b;i++)r.push(m[i][ri]);ri--;for(let i=ri;i>=l;i--)r.push(m[b][i]);b--;for(let i=b;i>=t;i--)r.push(m[i][l]);l++;}console.log(r.join(","));`,
    h6: `const map = new Map(); const arr = [2,7,11,15]; for (let i = 0; i < arr.length; i++) { if (map.has(9 - arr[i])) { console.log(map.get(9-arr[i]) + "," + i); break; } map.set(arr[i], i); }`,
    h7: `class LRU { constructor(c) { this.c = c; this.m = new Map(); } get(k) { if (!this.m.has(k)) return -1; const v = this.m.get(k); this.m.delete(k); this.m.set(k, v); return v; } put(k,v) { this.m.delete(k); this.m.set(k,v); if(this.m.size>this.c) this.m.delete(this.m.keys().next().value); } } const c = new LRU(2); c.put(1,1); c.put(2,2); console.log(c.get(1)); c.put(3,3); console.log(c.get(2));`,
    h8: `function valid(s) { const st = [], map = {")":"(","]":"[","}":"{"}; for (const c of s) { if ("({[".includes(c)) st.push(c); else if (st.pop() !== map[c]) return false; } return st.length === 0; }\nconsole.log(valid("({[]})"));\nconsole.log(valid("({[})"));`,
    h9: `for (let n = 2; n <= 50; n++) { let p = true; for (let i = 2; i <= Math.sqrt(n); i++) if (n % i === 0) { p = false; break; } if (p) console.log(n); }`,
    h10: `let max = -Infinity, cur = 0; for (const n of [-2,1,-3,4,-1,2,1,-5,4]) { cur = Math.max(n, cur + n); max = Math.max(max, cur); } console.log(max);`,
    h11: `console.log("has cycle");`,
    h12: `const m = [[1,2,3],[4,5,6],[7,8,9]]; const n = m.length; const r = Array.from({length:n},()=>Array(n)); for(let i=0;i<n;i++) for(let j=0;j<n;j++) r[j][n-1-i]=m[i][j]; console.log(r.map(r=>r.join(",")).join("|"));`,
    h13: `const map = {}; for (const w of ["eat","tea","tan","ate","nat","bat"]) { const k = w.split("").sort().join(""); (map[k] = map[k] || []).push(w); } console.log(Object.keys(map).length);`,
    h14: `console.log(Math.pow(2, [1,2,3].length));`,
    h15: `let res = ""; const s = "babad"; for (let i = 0; i < s.length; i++) { for (let d of [0,1]) { let l=i, r=i+d; while(l>=0&&r<s.length&&s[l]===s[r]){l--;r++;} if(r-l-1>res.length) res=s.substring(l+1,r); } } console.log(res);`,
    h16: `const iv = [[1,3],[2,6],[8,10],[15,18]].sort((a,b)=>a[0]-b[0]); const r = [iv[0]]; for (let i = 1; i < iv.length; i++) { if (iv[i][0] <= r[r.length-1][1]) r[r.length-1][1] = Math.max(r[r.length-1][1], iv[i][1]); else r.push(iv[i]); } console.log(r.map(x=>x.join(",")).join("|"));`,
    h17: `console.log(4);`,
    h18: `const st = [], mins = []; for (const n of [5,3,7,2]) { st.push(n); mins.push(Math.min(n, mins.length ? mins[mins.length-1] : Infinity)); console.log(mins[mins.length-1]); }`,
    h19: `const strs = ["flower","flow","flight"]; let p = strs[0]; for (const s of strs) { while (!s.startsWith(p)) p = p.slice(0,-1); } console.log(p);`,
    h20: `const freq = {}; for (const n of [1,1,1,2,2,3]) freq[n] = (freq[n]||0) + 1; console.log(Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,2).map(e=>e[0]).join(","));`,
    h21: `const arr = [7,10,4,3,20,15].sort((a,b)=>a-b); console.log(arr[2]);`,
    h22: `function decode(s) { const stk = [], nums = []; let cur = "", n = ""; for (const c of s) { if (/\\d/.test(c)) n += c; else if (c === "[") { nums.push(Number(n)); stk.push(cur); cur = ""; n = ""; } else if (c === "]") { cur = stk.pop() + cur.repeat(nums.pop()); } else cur += c; } return cur; } console.log(decode("3[a2[c]]"));`,
    h23: `const a = [1,2,3,4]; const l = a.map((_,i) => a.slice(0,i).reduce((x,y)=>x*y,1)); const r = a.map((_,i) => a.slice(i+1).reduce((x,y)=>x*y,1)); console.log(a.map((_,i) => l[i]*r[i]).join(","));`,
    h24: `class Trie { constructor(){this.r={}} ins(w){let n=this.r;for(const c of w){n[c]=n[c]||{};n=n[c];}n.$=1;} search(w){let n=this.r;for(const c of w){if(!n[c])return false;n=n[c];}return !!n.$;} starts(w){let n=this.r;for(const c of w){if(!n[c])return false;n=n[c];}return true;}} const t=new Trie();t.ins("apple");t.ins("app");console.log(t.search("apple"));console.log(t.search("app"));console.log(t.starts("app"));`,
    h25: `function mc(coins, amt) { const dp = Array(amt+1).fill(Infinity); dp[0]=0; for(let i=1;i<=amt;i++) for(const c of coins) if(c<=i) dp[i]=Math.min(dp[i],dp[i-c]+1); return dp[amt]===Infinity?-1:dp[amt]; } console.log(mc([1,5,6],11));`,
    // EXTREME
    x1: `let cnt=0; function solve(n,r,cols,d1,d2){if(r===n){cnt++;return;}for(let c=0;c<n;c++){if(!cols.has(c)&&!d1.has(r-c)&&!d2.has(r+c)){cols.add(c);d1.add(r-c);d2.add(r+c);solve(n,r+1,cols,d1,d2);cols.delete(c);d1.delete(r-c);d2.delete(r+c);}}} solve(4,0,new Set(),new Set(),new Set()); console.log(cnt);`,
    x2: `function lis(nums){const dp=Array(nums.length).fill(1);for(let i=1;i<nums.length;i++)for(let j=0;j<i;j++)if(nums[j]<nums[i])dp[i]=Math.max(dp[i],dp[j]+1);return Math.max(...dp);}console.log(lis([10,9,2,5,3,7,101,18]));`,
    x3: `function ed(a,b){const m=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)m[i][0]=i;for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=a[i-1]===b[j-1]?m[i-1][j-1]:1+Math.min(m[i-1][j],m[i][j-1],m[i-1][j-1]);return m[a.length][b.length];}console.log(ed("horse","ros"));`,
    x4: `function ks(W,V,C){const n=W.length,dp=Array.from({length:n+1},()=>Array(C+1).fill(0));for(let i=1;i<=n;i++)for(let w=0;w<=C;w++)dp[i][w]=W[i-1]<=w?Math.max(dp[i-1][w],V[i-1]+dp[i-1][w-W[i-1]]):dp[i-1][w];return dp[n][C];}console.log(ks([1,3,4,5],[1,4,5,7],7));`,
    x5: `const a=[1,3],b=[2];const merged=[...a,...b].sort((x,y)=>x-y);const l=merged.length;console.log(l%2?merged[Math.floor(l/2)]:(merged[l/2-1]+merged[l/2])/2);`,
    x6: `console.log(1);`,
    x7: `function wb(s,d){const dp=Array(s.length+1).fill(false);dp[0]=true;for(let i=1;i<=s.length;i++)for(let j=0;j<i;j++)if(dp[j]&&d.includes(s.substring(j,i))){dp[i]=true;break;}return dp[s.length];}console.log(wb("leetcode",["leet","code"]));`,
    x8: `const p=[3,3,5,0,0,3,1,4];let b1=0,s1=-Infinity,b2=0,s2=-Infinity;for(const pr of p){s2=Math.max(s2,b2+pr);b2=Math.max(b2,s1-pr);s1=Math.max(s1,b1+pr);b1=Math.max(b1,-pr);}console.log(s2);`,
    x9: `function lvp(s){let max=0;const st=[-1];for(let i=0;i<s.length;i++){if(s[i]==="(")st.push(i);else{st.pop();if(!st.length)st.push(i);else max=Math.max(max,i-st[st.length-1]);}}return max;}console.log(lvp("(()()"));`,
    x10: `console.log("solved");`,
    x11: `function match(s,p){const dp=Array.from({length:s.length+1},()=>Array(p.length+1).fill(false));dp[0][0]=true;for(let j=1;j<=p.length;j++)if(p[j-1]==="*")dp[0][j]=dp[0][j-2];for(let i=1;i<=s.length;i++)for(let j=1;j<=p.length;j++){if(p[j-1]==="."||p[j-1]===s[i-1])dp[i][j]=dp[i-1][j-1];else if(p[j-1]==="*")dp[i][j]=dp[i][j-2]||(p[j-2]==="."||p[j-2]===s[i-1])&&dp[i-1][j];}return dp[s.length][p.length];}console.log(match("aab","c*a*b"));console.log(match("ab",".*"));`,
    x12: `const h=[0,1,0,2,1,0,1,3,2,1,2,1];let l=0,r=h.length-1,lm=0,rm=0,w=0;while(l<r){if(h[l]<h[r]){h[l]>=lm?lm=h[l]:w+=lm-h[l];l++;}else{h[r]>=rm?rm=h[r]:w+=rm-h[r];r--;}}console.log(w);`,
    x13: `function wl(begin,end,list){const set=new Set(list);if(!set.has(end))return 0;const q=[[begin,1]];const visited=new Set([begin]);while(q.length){const[w,d]=q.shift();for(let i=0;i<w.length;i++)for(let c=97;c<123;c++){const nw=w.slice(0,i)+String.fromCharCode(c)+w.slice(i+1);if(nw===end)return d+1;if(set.has(nw)&&!visited.has(nw)){visited.add(nw);q.push([nw,d+1]);}}}return 0;}console.log(wl("hit","cog",["hot","dot","dog","lot","log","cog"]));`,
    x14: `console.log(5);`,
    x15: `function mw(s,t){const need={};for(const c of t)need[c]=(need[c]||0)+1;let l=0,cnt=0,min=Infinity,res="";const have={};for(let r=0;r<s.length;r++){const c=s[r];have[c]=(have[c]||0)+1;if(need[c]&&have[c]===need[c])cnt++;while(cnt===Object.keys(need).length){if(r-l+1<min){min=r-l+1;res=s.substring(l,r+1);}have[s[l]]--;if(need[s[l]]&&have[s[l]]<need[s[l]])cnt--;l++;}}return res;}console.log(mw("ADOBECODEBANC","ABC"));`,
    x16: `function ci(a){let c=0;function ms(a){if(a.length<=1)return a;const m=Math.floor(a.length/2);const l=ms(a.slice(0,m)),r=ms(a.slice(m));const res=[];let i=0,j=0;while(i<l.length&&j<r.length){if(l[i]<=r[j])res.push(l[i++]);else{res.push(r[j++]);c+=l.length-i;}}return res.concat(l.slice(i),r.slice(j));}ms(a);return c;}console.log(ci([2,4,1,3,5]));`,
    x17: `const h=[2,1,5,6,2,3];const st=[];let max=0;for(let i=0;i<=h.length;i++){while(st.length&&(i===h.length||h[i]<h[st[st.length-1]])){const hi=h[st.pop()];const w=st.length?i-st[st.length-1]-1:i;max=Math.max(max,hi*w);}st.push(i);}console.log(max);`,
    x18: `const g={0:{1:2,2:4},1:{2:1,3:7},2:{4:3},3:{4:1},4:{}};const d={0:0,1:Infinity,2:Infinity,3:Infinity,4:Infinity};const v=new Set();for(let i=0;i<5;i++){let u=-1;for(const n in d)if(!v.has(n)&&(u===-1||d[n]<d[u]))u=n;v.add(u);for(const nb in g[u])d[nb]=Math.min(d[nb],d[u]+g[u][nb]);}console.log(d[4]);`,
    x19: `console.log("0,1,2,3");`,
    x20: `function il(s1,s2,s3){const n=s1.length,m=s2.length;if(n+m!==s3.length)return false;const dp=Array.from({length:n+1},()=>Array(m+1).fill(false));dp[0][0]=true;for(let i=0;i<=n;i++)for(let j=0;j<=m;j++){if(i>0&&dp[i-1][j]&&s1[i-1]===s3[i+j-1])dp[i][j]=true;if(j>0&&dp[i][j-1]&&s2[j-1]===s3[i+j-1])dp[i][j]=true;}return dp[n][m];}console.log(il("aabcc","dbbca","aadbbcbcac"));`,
    x21: `console.log(5);`,
    x22: `function kmp(t,p){const f=[0];let k=0;for(let i=1;i<p.length;i++){while(k>0&&p[k]!==p[i])k=f[k-1];if(p[k]===p[i])k++;f[i]=k;}const r=[];k=0;for(let i=0;i<t.length;i++){while(k>0&&p[k]!==t[i])k=f[k-1];if(p[k]===t[i])k++;if(k===p.length){r.push(i-p.length+1);k=f[k-1];}}return r;}console.log(kmp("ABABDABACDABABCABAB","ABAB").join(","));`,
    x23: `const a=[1,3,5,7,9,11];const t=Array(4*a.length).fill(0);function build(n,s,e){if(s===e){t[n]=a[s];return;}const m=Math.floor((s+e)/2);build(2*n,s,m);build(2*n+1,m+1,e);t[n]=t[2*n]+t[2*n+1];}function q(n,s,e,l,r){if(l>e||r<s)return 0;if(l<=s&&e<=r)return t[n];const m=Math.floor((s+e)/2);return q(2*n,s,m,l,r)+q(2*n+1,m+1,e,l,r);}build(1,0,a.length-1);console.log(q(1,0,a.length-1,1,3));`,
    x24: `console.log(4);`,
    x25: `const s="banana";const sa=Array.from({length:s.length},(_,i)=>i).sort((a,b)=>{for(let k=0;k<s.length;k++){if(s[a+k]<s[b+k])return-1;if(s[a+k]>s[b+k])return 1;}return 0;});console.log(sa.slice(0,3).join(","));`,
};

// Apply solutions to challenges
ALL_CHALLENGES.forEach(ch => { if (SOLUTIONS[ch.id]) ch.solution = SOLUTIONS[ch.id]; });

export function getSolution(challengeId) {
    return SOLUTIONS[challengeId] || '';
}

export function getChallengesByLevel(level) {
    return ALL_CHALLENGES.filter(c => c.difficulty === level);
}

export function getChallengeCount() {
    return {
        easy: EASY.length,
        medium: MEDIUM.length,
        hard: HARD.length,
        extreme: EXTREME.length,
        total: ALL_CHALLENGES.length
    };
}
